import { Department, Impact, Patient } from "./types";

export const departments: Department[] = [
  { id: "pt", name: "العلاج الطبيعي" },
  { id: "resp", name: "العلاج التنفسي" },
  { id: "nutrition", name: "التغذية العلاجية" },
  { id: "speech", name: "علاج النطق والبلع" },
  { id: "nursing", name: "التمريض" },
  { id: "neuro", name: "طب الأعصاب" },
  { id: "wound", name: "عناية الجروح" },
];

export const patients: Patient[] = [
  {
    id: "p1",
    mrn: "MRN-10234",
    name: "سالم عبدالله القحطاني",
    admissionDate: "2026-05-02",
    department: "pt",
    status: "active",
  },
  {
    id: "p2",
    mrn: "MRN-10567",
    name: "فاطمة أحمد الزهراني",
    admissionDate: "2026-04-18",
    department: "neuro",
    status: "followup",
  },
  {
    id: "p3",
    mrn: "MRN-10812",
    name: "محمد ناصر العتيبي",
    admissionDate: "2026-06-01",
    department: "resp",
    status: "active",
  },
  {
    id: "p4",
    mrn: "MRN-11023",
    name: "نورة سعد الدوسري",
    admissionDate: "2026-03-11",
    department: "speech",
    status: "discharged",
  },
  {
    id: "p5",
    mrn: "MRN-11244",
    name: "خالد إبراهيم الشهري",
    admissionDate: "2026-07-05",
    department: "wound",
    status: "active",
  },
];

export const impacts: Impact[] = [
  {
    id: "i1",
    patientId: "p1",
    eventDate: "2026-05-05",
    previousStatus: "طريح الفراش",
    whatChanged: "بدأ برنامج تأهيل حركي مبكر بإشراف العلاج الطبيعي",
    currentOutcome: "الجلوس بمساعدة على حافة السرير",
    category: "mobility",
    departments: ["pt", "nursing"],
    description: "استجابة جيدة للتحفيز الحركي المبكر بعد استقرار الحالة.",
    documentationSource: "تقرير العلاج الطبيعي",
    evidenceRef: "ملف تقييم PT-05-05-2026.pdf",
    status: "approved",
    createdAt: "2026-05-05T09:12:00Z",
    reviewedAt: "2026-05-05T14:00:00Z",
  },
  {
    id: "i2",
    patientId: "p1",
    eventDate: "2026-05-14",
    previousStatus: "الجلوس بمساعدة",
    whatChanged: "تحسّن التوازن الجذعي وقوة الأطراف السفلية",
    currentOutcome: "الوقوف بمساعدة جهاز مشي",
    category: "mobility",
    departments: ["pt"],
    description: "قادر على الوقوف لمدة دقيقتين بمساعدة كامل.",
    documentationSource: "تقرير العلاج الطبيعي",
    status: "approved",
    createdAt: "2026-05-14T10:00:00Z",
    reviewedAt: "2026-05-14T16:20:00Z",
  },
  {
    id: "i3",
    patientId: "p1",
    eventDate: "2026-05-25",
    previousStatus: "الوقوف بمساعدة",
    whatChanged: "استمرار جلسات التأهيل اليومية مع تمارين المشي المتدرج",
    currentOutcome: "المشي بمساعدة جهاز مشي لمسافة قصيرة",
    category: "mobility",
    departments: ["pt", "nursing"],
    description: "أول محاولة مشي ناجحة داخل الغرفة لمسافة 5 أمتار.",
    documentationSource: "ملاحظات التمريض",
    status: "approved",
    createdAt: "2026-05-25T08:40:00Z",
    reviewedAt: "2026-05-25T13:10:00Z",
  },
  {
    id: "i4",
    patientId: "p1",
    eventDate: "2026-06-10",
    previousStatus: "المشي بمساعدة جهاز مشي",
    whatChanged: "تحسّن ملحوظ في الثقة والقدرة على التحمل",
    currentOutcome: "المشي المستقل داخل القسم",
    category: "functional",
    departments: ["pt"],
    description: "أصبح المريض قادرًا على المشي دون مساعدة داخل الممر.",
    documentationSource: "تقرير العلاج الطبيعي",
    status: "pending",
    createdAt: "2026-06-10T11:05:00Z",
  },
  {
    id: "i5",
    patientId: "p2",
    eventDate: "2026-04-25",
    previousStatus: "فقدان النطق التام",
    whatChanged: "بدء جلسات علاج النطق المكثفة",
    currentOutcome: "القدرة على نطق كلمات مفردة بوضوح",
    category: "communication",
    departments: ["speech", "neuro"],
    description: "استجابة إيجابية لتمارين التحفيز اللغوي المبكر.",
    documentationSource: "تقرير علاج النطق والبلع",
    status: "approved",
    createdAt: "2026-04-25T09:30:00Z",
    reviewedAt: "2026-04-26T09:00:00Z",
  },
  {
    id: "i6",
    patientId: "p2",
    eventDate: "2026-05-20",
    previousStatus: "نطق كلمات مفردة",
    whatChanged: "تطور القدرة على تكوين جمل قصيرة",
    currentOutcome: "التواصل بجمل قصيرة مفهومة",
    category: "communication",
    departments: ["speech"],
    description: "تحسّن كبير في الطلاقة اللفظية خلال أربعة أسابيع.",
    documentationSource: "تقرير علاج النطق والبلع",
    status: "approved",
    createdAt: "2026-05-20T10:15:00Z",
    reviewedAt: "2026-05-21T08:45:00Z",
  },
  {
    id: "i7",
    patientId: "p3",
    eventDate: "2026-06-05",
    previousStatus: "اعتماد كامل على جهاز التنفس الصناعي",
    whatChanged: "نجاح تجربة فطام تدريجي عن جهاز التنفس",
    currentOutcome: "التنفس الذاتي مع دعم أكسجين بسيط",
    category: "respiratory",
    departments: ["resp", "nursing"],
    description: "خطوة مهمة نحو استقلالية الجهاز التنفسي.",
    documentationSource: "تقرير العلاج التنفسي",
    status: "approved",
    createdAt: "2026-06-05T07:50:00Z",
    reviewedAt: "2026-06-05T15:30:00Z",
  },
  {
    id: "i8",
    patientId: "p3",
    eventDate: "2026-06-20",
    previousStatus: "التنفس الذاتي مع دعم أكسجين",
    whatChanged: "استقرار مؤشرات الأكسجين دون الحاجة لدعم إضافي",
    currentOutcome: "التنفس الذاتي الكامل دون دعم أكسجين",
    category: "respiratory",
    departments: ["resp"],
    description: "تم قطع الأكسجين التكميلي بنجاح مع بقاء التشبع ضمن المعدل الطبيعي.",
    documentationSource: "ملاحظات الطبيب المعالج",
    status: "pending",
    createdAt: "2026-06-20T12:00:00Z",
  },
  {
    id: "i9",
    patientId: "p4",
    eventDate: "2026-03-20",
    previousStatus: "عدم القدرة على البلع الآمن",
    whatChanged: "برنامج تأهيل بلع تدريجي بإشراف أخصائي النطق والبلع",
    currentOutcome: "القدرة على تناول أغذية ناعمة بأمان",
    category: "nutrition",
    departments: ["speech", "nutrition"],
    description: "اجتياز اختبار البلع السريري دون علامات شفط.",
    documentationSource: "تقرير أخصائي التغذية",
    status: "approved",
    createdAt: "2026-03-20T09:00:00Z",
    reviewedAt: "2026-03-21T09:00:00Z",
  },
  {
    id: "i10",
    patientId: "p5",
    eventDate: "2026-07-10",
    previousStatus: "جرح مفتوح بمرحلة التهابية",
    whatChanged: "بروتوكول عناية متقدم بالجروح وتغيير ضمادات متخصص",
    currentOutcome: "بدء مرحلة نمو الأنسجة الحبيبية",
    category: "wound",
    departments: ["wound", "nursing"],
    description: "تحسن ملحوظ في مظهر الجرح وانخفاض الإفرازات.",
    documentationSource: "ملاحظات التمريض",
    status: "approved",
    createdAt: "2026-07-10T08:20:00Z",
    reviewedAt: "2026-07-10T17:00:00Z",
  },
  {
    id: "i11",
    patientId: "p5",
    eventDate: "2026-07-28",
    previousStatus: "نمو أنسجة حبيبية",
    whatChanged: "استمرار العناية المتخصصة وتحسّن التروية الدموية",
    currentOutcome: "بدء مرحلة التقفّل الحوافي للجرح",
    category: "wound",
    departments: ["wound"],
    description: "تقلص واضح في مساحة الجرح خلال أسبوعين.",
    documentationSource: "تقرير العلاج التنفسي",
    status: "rejected",
    rejectionReason: "التحسن ضمن السياق الطبيعي للعلاج ولا يمثل نقطة تحول مؤثرة سريريًا بعد.",
    createdAt: "2026-07-28T10:00:00Z",
    reviewedAt: "2026-07-29T09:00:00Z",
  },
];
